export enum ModuleKey {
    DASHBOARD = "DASHBOARD",
    CREATE_PO = "CREATE_PO",
    PURCHASE_ORDERS = "PURCHASE_ORDERS",
    SPECIAL_ORDERS = "SPECIAL_ORDERS",
    GRN_RTV = "GRN_RTV",
    INVENTORY_MASTER = "INVENTORY_MASTER",
    VENDOR_MANAGEMENT = "VENDOR_MANAGEMENT",
    CREATE_INDENT = "CREATE_INDENT",
    APPROVE_INDENTS = "APPROVE_INDENTS",
    ISSUE_STOCK = "ISSUE_STOCK",
    WORK_AREAS = "WORK_AREAS",
    REPORTS = "REPORTS",
    USERS = "USERS",
    BRANCHES = "BRANCHES",
    SYSTEM_LOGS = "SYSTEM_LOGS"
}
