import { ExcelColumn } from '../excel/excel.service';

export const stockColumns: ExcelColumn[] = [
    { header: "S.No", key: "sNo", type: "number" },
    { header: "Location", key: "branch", type: "string" },
    { header: "Category", key: "category", type: "string" },
    { header: "Sub Category", key: "subCategory", type: "string" },
    { header: "HSN/SAC", key: "hsnCode", type: "string" },
    { header: "Item Code", key: "itemCode", type: "string" },
    { header: "Item Name", key: "itemName", type: "string" },
    { header: "Entry Type", key: "entryType", type: "string" },
    { header: "Package Name", key: "packageName", type: "string" },
    { header: "UOM", key: "uom", type: "string" },
    { header: "Tax(%)", key: "taxRate", type: "number" },
    { header: "Store Stock", key: "qty_store", type: "number" },
    { header: "WAC(incl.tax,etc)", key: "wac", type: "number" },
    { header: "Store Total(incl.tax,etc)", key: "total_store", type: "number" },
    { header: "BAR", key: "qty_bar", type: "number" },
    { header: "BAR Total(incl.tax,etc)", key: "total_bar", type: "number" },
    { header: "STAFF_KITCHEN", key: "qty_staff_kitchen", type: "number" },
    { header: "STAFF_KITCHEN Total(incl.tax,etc)", key: "total_staff_kitchen", type: "number" },
    { header: "BAKERY", key: "qty_bakery", type: "number" },
    { header: "BAKERY Total(incl.tax,etc)", key: "total_bakery", type: "number" },
    { header: "MAIN_KITCHEN", key: "qty_main_kitchen", type: "number" },
    { header: "MAIN_KITCHEN Total(incl.tax,etc)", key: "total_main_kitchen", type: "number" },
    { header: "F&B SERVICE", key: "qty_f_b_service", type: "number" },
    { header: "F&B SERVICE Total(incl.tax,etc)", key: "total_f_b_service", type: "number" },
    { header: "BARISTA", key: "qty_barista", type: "number" },
    { header: "BARISTA Total(incl.tax,etc)", key: "total_barista", type: "number" },
    { header: "KST", key: "qty_kst", type: "number" },
    { header: "KST Total(incl.tax,etc)", key: "total_kst", type: "number" },
    { header: "HOUSE_KEEPING", key: "qty_house_keeping", type: "number" },
    { header: "HOUSE_KEEPING Total(incl.tax,etc)", key: "total_house_keeping", type: "number" },
    { header: "Total Stock(Store + Workarea)", key: "totalStock", type: "number" },
    { header: "Grand Total(incl.tax,etc)", key: "grandTotal", type: "number" }
];
